version: "3.5"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8001:8000"
      - "443:443"
    volumes:
      - ./:/var/www/app
      - ./docker/conf:/etc/nginx/conf.d
      - ./docker/nginx_logs:/var/log/nginx
      - ./docker/ssl:/etc/nginx/ssl
    links:
      - fpm
#    restart: unless-stopped
  fpm:
    build:
      context: ./
      dockerfile: docker/php81-fpm.Dockerfile
    volumes:
      - ./:/var/www/app:cached
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PHP_INI_SCAN_DIR=./docker:/usr/local/etc/php/conf.d
    links:
      - redis
    restart: unless-stopped
  redis:
    container_name: redis-alpine
    image: i386/redis:6.0.19-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
